# Generated by Django 5.2.17 on 2026-09-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournament_swiss_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='default_format',
            field=models.CharField(choices=[('KNOCKOUT', 'Single-elimination bracket'), ('ROUND_ROBIN', 'Round-robin points table'), ('TIME_TRIAL', 'Time-trial / leaderboard'), ('SINGLE_EVENT', 'Single-event ranking'), ('SWISS', 'Swiss pairing')], default='KNOCKOUT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('KNOCKOUT', 'Single-elimination bracket'), ('ROUND_ROBIN', 'Round-robin points table'), ('TIME_TRIAL', 'Time-trial / leaderboard'), ('SINGLE_EVENT', 'Single-event ranking'), ('SWISS', 'Swiss pairing')], max_length=20),
        ),
    ]
