# Generated by Django 5.2.17 on 2026-09-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_sport_default_format_alter_tournament_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='set_scores',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fixture',
            name='sets_to_win',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='draw_category',
            field=models.CharField(blank=True, choices=[('SINGLES', 'Singles'), ('DOUBLES', 'Doubles'), ('MIXED_DOUBLES', 'Mixed Doubles'), ('WOMENS', "Women's")], max_length=20),
        ),
    ]
