# Generated by Django 5.2.17 on 2026-09-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_fixture_set_scores_fixture_sets_to_win_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualregistration',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional contact number', max_length=20),
        ),
    ]
