# Generated by Django 5.2.17 on 2026-09-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_individualregistration_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualregistration',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Manually entered skill rating for entrants without an account (e.g. chess FIDE rating).', null=True),
        ),
    ]
