# Generated by Django 5.2.17 on 2026-09-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_individualregistration_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='match_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
