# Generated by Django 5.2.17 on 2026-10-03 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_fixturecommentatorassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='individualregistration',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='individualregistration',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='individualregistration',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='individualregistration',
            name='refund_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='individualregistration',
            name='removal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='individualregistration',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualregistration',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sport',
            name='allow_pair_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='allow_player_created_teams',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='allow_substitutes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='max_active_players',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='max_bench_players',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='max_team_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='min_active_players',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='participation_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('PAIR', 'Pair / Joint'), ('TEAM', 'Team')], default='TEAM', max_length=15),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_pair',
            field=models.BooleanField(default=False, help_text='True if this is a temporary pair rather than a permanent team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='roster_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BENCHED', 'Benched')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='allow_pair_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='allow_player_created_teams',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='allow_substitutes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_active_players',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_bench_players',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_team_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_active_players',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participation_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('PAIR', 'Pair / Joint'), ('TEAM', 'Team')], default='TEAM', max_length=15),
        ),
        migrations.AddField(
            model_name='tournamentteamentry',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tournamentteamentry',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentteamentry',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tournamentteamentry',
            name='refund_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentteamentry',
            name='removal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournamentteamentry',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentteamentry',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='individualregistration',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_SUCCESS', 'Payment Success'), ('APPROVED', 'Approved'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('REMOVED', 'Removed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentteamentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_SUCCESS', 'Payment Success'), ('APPROVED', 'Approved'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('REMOVED', 'Removed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='APPROVED', max_length=20),
        ),
    ]
