# Generated by Django 5.2.17 on 2026-10-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_remove_team_captain_team_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('CAPTAIN', 'Captain'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
    ]
