# Generated by Django 5.2.17 on 2026-10-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_teamjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualregistration',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
    ]
