# Generated by Django 5.2.17 on 2026-10-10 02:03

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_fixturerefereeassignment_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturecommentatorassignment',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fixturecommentatorassignment',
            name='role',
            field=models.CharField(choices=[('LEAD', 'Lead Play-by-Play Caster'), ('COLOR', 'Color Analyst / Co-Host'), ('SIDELINE', 'Sideline Reporter / Guest')], default='LEAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchauditlog',
            name='new_state',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='matchauditlog',
            name='previous_state',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.CreateModel(
            name='CommentaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General Commentary'), ('KEY_MOMENT', 'Key Moment'), ('MATCH_UPDATE', 'Match Update'), ('ANALYSIS', 'Match Analysis')], default='GENERAL', max_length=30)),
                ('score_snapshot', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('match_clock', models.CharField(blank=True, max_length=60)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentary_entries', to=settings.AUTH_USER_MODEL)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentary_entries', to='tournaments.fixture')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['fixture', 'created_at'], name='tournaments_fixture_5b3bd0_idx'), models.Index(fields=['fixture', 'is_deleted'], name='tournaments_fixture_5cde78_idx')],
            },
        ),
        migrations.CreateModel(
            name='TournamentCommentatorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentators_registered', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_commentators', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_commentator_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'user'), name='uniq_tournament_commentator_registration')],
            },
        ),
    ]
