# Generated by Django 5.2.17 on 2026-09-07 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_playerprofile_rating_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organizers/covers/'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organizers/'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/covers/'),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_notifications',
            field=models.BooleanField(default=True, help_text='Deliver notifications as a push notification, not just in-app.'),
        ),
        migrations.CreateModel(
            name='UserFCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('desktop', 'Desktop')], default='web', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
