# Generated by Django 5.2.17 on 2026-09-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizerprofile_cover_photo_and_more'),
        ('tournaments', '0017_fixture_match_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='followed_sports',
            field=models.ManyToManyField(blank=True, related_name='followers', to='tournaments.sport'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='Position or specialization', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.IntegerField(blank=True, help_text='6-digit unique permanent ID', null=True, unique=True),
        ),
    ]
