# Generated by Django 5.2.17 on 2026-09-30 11:29

import random
from django.db import migrations

def backfill_uids(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    existing_uids = set(User.objects.exclude(uid__isnull=True).values_list('uid', flat=True))
    
    users_to_update = []
    for user in User.objects.filter(uid__isnull=True):
        while True:
            new_uid = random.randint(100000, 999999)
            if new_uid not in existing_uids:
                existing_uids.add(new_uid)
                user.uid = new_uid
                user.is_email_verified = True
                users_to_update.append(user)
                break
                
    User.objects.bulk_update(users_to_update, ['uid', 'is_email_verified'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp_playerprofile_followed_sports_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_uids, reverse_code=migrations.RunPython.noop),
    ]
