# Generated by Django 5.2.17 on 2026-09-30 11:45

from django.db import migrations

def backfill_settings(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    UserSettings = apps.get_model('accounts', 'UserSettings')
    
    settings_to_create = []
    for user in User.objects.filter(settings__isnull=True):
        settings_to_create.append(UserSettings(user=user))
        
    UserSettings.objects.bulk_create(settings_to_create)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usersettings_userfollow'),
    ]

    operations = [
        migrations.RunPython(backfill_settings, reverse_code=migrations.RunPython.noop),
    ]
