# Generated by Django 5.2.17 on 2026-09-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20260930_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='city',
            new_name='current_city',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='home_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='workplace',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
