# Generated by Django 5.2.17 on 2026-09-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_fix_json_fields_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='college',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='school',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='workplace',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
