# Generated by Django 5.2.17 on 2026-10-10 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_playerprofile_college_and_more'),
        ('tournaments', '0024_fixturerefereeassignment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefereeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('experience_level', models.CharField(choices=[('GRASSEROOTS', 'Grassroots / Amateur'), ('REGIONAL', 'Regional / State Level'), ('NATIONAL', 'National Level'), ('INTERNATIONAL', 'International / Professional')], default='GRASSEROOTS', max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Years of officiating experience')),
                ('certifications', models.TextField(blank=True, help_text='Qualifications, badges or referee certifications')),
                ('preferred_location', models.CharField(blank=True, max_length=120)),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Official certification verified by platform')),
                ('sports', models.ManyToManyField(blank=True, related_name='referees', to='tournaments.sport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
