# Generated by Django 5.2.17 on 2026-10-10 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_refereeprofile'),
        ('tournaments', '0025_fixturecommentatorassignment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('experience_level', models.CharField(choices=[('ROOKIE', 'Rookie / College Media'), ('REGIONAL', 'Regional / Club Broadcaster'), ('NATIONAL', 'National Streamer / Caster'), ('PROFESSIONAL', 'Professional / TV Broadcast')], default='ROOKIE', max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Years of casting/commentary experience')),
                ('languages', models.CharField(blank=True, help_text='e.g. English, Hindi, Spanish', max_length=200)),
                ('social_handle', models.CharField(blank=True, help_text='Twitter/Twitch/YouTube handle', max_length=100)),
                ('sample_reel_url', models.URLField(blank=True, help_text='Link to audio/video commentary portfolio')),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Official caster verified by platform')),
                ('sports', models.ManyToManyField(blank=True, related_name='commentators', to='tournaments.sport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commentator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
