# Generated by Django 5.2.17 on 2026-09-06 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('PLAYER', 'Player'), ('ORGANIZER', 'Organizer')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Registration issue', 'Registration issue'), ('Registration not showing', 'Registration not showing'), ('Profile information correction', 'Profile information correction'), ('Team joining issue', 'Team joining issue'), ('Wrong team assignment', 'Wrong team assignment'), ('Match/fixture not found', 'Match/fixture not found'), ('Match schedule change', 'Match schedule change'), ('Wrong opponent or bracket', 'Wrong opponent or bracket'), ('Incorrect match score', 'Incorrect match score'), ('Match result not updated', 'Match result not updated'), ('Live score not updating', 'Live score not updating'), ('Notification not received', 'Notification not received'), ('Tournament information request', 'Tournament information request'), ('Payment/registration fee issue', 'Payment/registration fee issue'), ('Tournament status issue', 'Tournament status issue'), ('Tournament creation issue', 'Tournament creation issue'), ('Tournament setup issue', 'Tournament setup issue'), ('Registration management', 'Registration management'), ('Player management', 'Player management'), ('Team management', 'Team management'), ('Fixture scheduling issue', 'Fixture scheduling issue'), ('Bracket management', 'Bracket management'), ('Match assignment issue', 'Match assignment issue'), ('Score/result management', 'Score/result management'), ('Live score issue', 'Live score issue'), ('Tournament standings issue', 'Tournament standings issue'), ('Payment/payout issue', 'Payment/payout issue'), ('Venue management', 'Venue management'), ('Notification issue', 'Notification issue'), ('Tournament cancellation or postponement', 'Tournament cancellation or postponement')], max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, help_text='Shown to the requester in the closing email.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='support/%Y/%m/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
