# Generated by Django 5.2.17 on 2026-09-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_remove_sitesetting_maintenance_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='support_email',
            field=models.EmailField(default='support@tournamentsc.com', max_length=254),
        ),
    ]
