# Generated by Django 5.2.17 on 2026-10-04 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_playerprofile_college_and_more'),
        ('content', '0003_backfill_achievements'),
        ('tournaments', '0023_individualregistration_email_teammembership_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='organizer_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_content', to='accounts.organizerprofile'),
        ),
        migrations.AddField(
            model_name='content',
            name='team_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_content', to='tournaments.team'),
        ),
    ]
