# Generated by Django 5.2.17 on 2026-10-09 22:30

import content.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_organizer_author_content_team_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='aspect_ratio',
            field=models.CharField(blank=True, default='1/1', max_length=10),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('post', 'Post'), ('carousel', 'Carousel')], default='post', max_length=10),
        ),
        migrations.CreateModel(
            name='ContentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.FileField(upload_to='content/media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'mp4', 'mov', 'webm']), content.validators.validate_content_media_size])),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='content.content')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
