# Generated by Django 5.2.17 on 2026-10-09 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_aspect_ratio_alter_content_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_in_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('post', 'Post'), ('carousel', 'Carousel'), ('short', 'Short Video'), ('full_video', 'Full Video')], default='post', max_length=15),
        ),
    ]
