# Generated by Django 5.2.17 on 2026-10-10 01:07

import content.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_content_tagged_users_content_video_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='content/media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'mp4', 'mov', 'webm', 'm4v', 'avi', 'mkv', 'heic', 'heif']), content.validators.validate_content_media_size]),
        ),
        migrations.AlterField(
            model_name='contentmedia',
            name='media_file',
            field=models.FileField(upload_to='content/media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'mp4', 'mov', 'webm', 'm4v', 'avi', 'mkv', 'heic', 'heif']), content.validators.validate_content_media_size]),
        ),
    ]
